name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - id: publish
        name: Release to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          tag: beta
      - name: Tag successful release
        if: steps.publish.outputs.version != steps.publish.outputs.old-version
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{ steps.publish.outputs.version }}
          message: 'Latest v${{ steps.publish.outputs.version }}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
